2025-03-25 22:57:38,001 - 20250325_225738 - D√©but traitement demande 20250325_225738
2025-03-25 22:57:38,001 - 20250325_225738 - Chargement des donn√©es
2025-03-25 22:57:47,474 - 20250325_225738 - Pr√©traitement des donn√©es
2025-03-25 22:57:47,595 - 20250325_225738 - Construction du mod√®le
2025-03-25 22:57:48,915 - 20250325_225738 - √âvaluation du mod√®le
2025-03-25 22:57:49,455 - 20250325_225738 - Traitement r√©ussi 20250325_225738
2025-03-28 19:45:34,580 - 20250328_194534 - D√©but traitement demande 20250328_194534
2025-03-28 19:45:34,580 - 20250328_194534 - Chargement des donn√©es
2025-03-28 19:45:50,291 - 20250328_194534 - Pr√©traitement des donn√©es
2025-03-28 19:45:51,078 - 20250328_194534 - √âvaluation du mod√®le
2025-03-28 19:45:51,113 - 20250328_194534 - √âchec traitement: name 'np' is not defined
2025-03-28 20:48:02,326 - 20250328_204802 - D√©but traitement demande 20250328_204802
2025-03-28 20:48:02,326 - 20250328_204802 - Chargement des donn√©es
2025-03-28 20:48:02,335 - 20250328_204802 - Pr√©traitement des donn√©es
2025-03-28 20:48:02,336 - 20250328_204802 - √âchec traitement: "['Price'] not found in axis"
2025-03-28 20:48:44,518 - 20250328_204844 - D√©but traitement demande 20250328_204844
2025-03-28 20:48:44,519 - 20250328_204844 - Chargement des donn√©es
2025-03-28 20:48:44,528 - 20250328_204844 - Pr√©traitement des donn√©es
2025-03-28 20:48:44,529 - 20250328_204844 - √âchec traitement: "['Price'] not found in axis"
2025-03-28 21:21:42,173 - 20250328_212142 - D√©but traitement demande 20250328_212142
2025-03-28 21:21:42,173 - 20250328_212142 - Chargement des donn√©es
2025-03-28 21:21:42,182 - 20250328_212142 - Pr√©traitement des donn√©es
2025-03-28 21:21:42,183 - 20250328_212142 - √âchec traitement: "['Price'] not found in axis"
2025-03-28 21:38:03,322 - 20250328_213803 - D√©but traitement demande 20250328_213803
2025-03-28 21:38:03,322 - 20250328_213803 - Chargement des donn√©es
2025-03-28 21:38:03,332 - 20250328_213803 - Pr√©traitement des donn√©es
2025-03-28 21:38:03,341 - 20250328_213803 - √âchec traitement: could not convert string to float: 'yes'
2025-03-28 22:02:00,503 - 20250328_220200 - D√©but traitement demande 20250328_220200
2025-03-28 22:02:00,503 - 20250328_220200 - Chargement des donn√©es
2025-03-28 22:02:15,864 - 20250328_220200 - Pr√©traitement des donn√©es
2025-03-28 22:02:16,537 - 20250328_220200 - √âvaluation du mod√®le
2025-03-28 22:02:17,183 - 20250328_220217 - D√©but traitement demande 20250328_220217
2025-03-28 22:02:17,183 - 20250328_220217 - Chargement des donn√©es
2025-03-28 22:02:17,189 - 20250328_220217 - Pr√©traitement des donn√©es
2025-03-28 22:02:17,486 - 20250328_220217 - √âvaluation du mod√®le
2025-03-29 02:17:50 - 20250329_021750 - INFO - D√©but traitement demande 20250329_021750
2025-03-29 02:17:50 - 20250329_021750 - INFO - Chargement des donn√©es
2025-03-29 02:17:52 - 20250329_021750 - ERROR - Erreur de chargement: name 'save_artifact' is not defined
Traceback (most recent call last):
  File "/home/nango/Documents/Cours_M2_IA/Cours_outils_versionning/Exam/ml_project_back.py", line 146, in load_data
    save_artifact(df, DATA_DIR / f"raw_data_{request_id}.csv", request_id)
    ^^^^^^^^^^^^^
NameError: name 'save_artifact' is not defined
2025-03-29 02:19:14 - 20250329_021914 - INFO - D√©but traitement demande 20250329_021914
2025-03-29 02:19:14 - 20250329_021914 - INFO - Chargement des donn√©es
2025-03-29 02:19:16 - 20250329_021914 - ERROR - Erreur de chargement: name 'save_artifact' is not defined
Traceback (most recent call last):
  File "/home/nango/Documents/Cours_M2_IA/Cours_outils_versionning/Exam/ml_project_back.py", line 148, in load_data
    save_artifact(df, DATA_DIR / f"raw_data_{request_id}.csv", request_id)
    ^^^^^^^^^^^^^
NameError: name 'save_artifact' is not defined
2025-03-29 02:22:07 - 20250329_022207 - INFO - D√©but traitement demande 20250329_022207
2025-03-29 02:22:07 - 20250329_022207 - INFO - Chargement des donn√©es
2025-03-29 02:22:22 - 20250329_022207 - ERROR - √âchec traitement: name 'preprocess_data' is not defined
Traceback (most recent call last):
  File "/home/nango/Documents/Cours_M2_IA/Cours_outils_versionning/Exam/ml_project_back.py", line 103, in process_client_request
    X_train, X_test, y_train, y_test = preprocess_data(
                                       ^^^^^^^^^^^^^^^
NameError: name 'preprocess_data' is not defined
2025-03-29 02:22:22 - 20250329_022222 - INFO - D√©but traitement demande 20250329_022222
2025-03-29 02:22:22 - 20250329_022222 - INFO - Chargement des donn√©es
2025-03-29 02:22:22 - 20250329_022222 - ERROR - √âchec traitement: name 'preprocess_data' is not defined
Traceback (most recent call last):
  File "/home/nango/Documents/Cours_M2_IA/Cours_outils_versionning/Exam/ml_project_back.py", line 103, in process_client_request
    X_train, X_test, y_train, y_test = preprocess_data(
                                       ^^^^^^^^^^^^^^^
NameError: name 'preprocess_data' is not defined
2025-03-29 16:02:23 - 20250329_160223 - INFO - DÈbut traitement demande 20250329_160223
2025-03-29 16:02:23 - 20250329_160223 - INFO - Chargement des donnÈes
2025-03-29 16:02:23 - 20250329_160223 - ERROR - Erreur de chargement: No columns to parse from file
Traceback (most recent call last):
  File "E:\00.Divers\DIT\04.Cours\M2\03.OutilsDeVersionning\Examen\Dev\DIT_VERSION_TOOLS\ml_project_back.py", line 164, in load_data
    df = pd.read_csv(file_path)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 1679, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas\_libs\parsers.pyx", line 557, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
2025-03-29 16:02:23 - 20250329_160223 - ERROR - …chec traitement: No columns to parse from file
Traceback (most recent call last):
  File "E:\00.Divers\DIT\04.Cours\M2\03.OutilsDeVersionning\Examen\Dev\DIT_VERSION_TOOLS\ml_project_back.py", line 106, in process_client_request
    df = load_data(data_file_path, request_id)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\00.Divers\DIT\04.Cours\M2\03.OutilsDeVersionning\Examen\Dev\DIT_VERSION_TOOLS\ml_project_back.py", line 164, in load_data
    df = pd.read_csv(file_path)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 1679, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas\_libs\parsers.pyx", line 557, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
2025-03-29 16:51:57 - 20250329_165157 - INFO - DÈbut traitement demande 20250329_165157
2025-03-29 16:51:57 - 20250329_165157 - INFO - Chargement des donnÈes
2025-03-29 16:51:57 - 20250329_165157 - ERROR - Erreur de chargement: No columns to parse from file
Traceback (most recent call last):
  File "E:\00.Divers\DIT\04.Cours\M2\03.OutilsDeVersionning\Examen\Dev\DIT_VERSION_TOOLS\ml_project_back.py", line 164, in load_data
    df = pd.read_csv(file_path)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 1679, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas\_libs\parsers.pyx", line 557, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
2025-03-29 16:51:57 - 20250329_165157 - ERROR - …chec traitement: No columns to parse from file
Traceback (most recent call last):
  File "E:\00.Divers\DIT\04.Cours\M2\03.OutilsDeVersionning\Examen\Dev\DIT_VERSION_TOOLS\ml_project_back.py", line 106, in process_client_request
    df = load_data(data_file_path, request_id)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\00.Divers\DIT\04.Cours\M2\03.OutilsDeVersionning\Examen\Dev\DIT_VERSION_TOOLS\ml_project_back.py", line 164, in load_data
    df = pd.read_csv(file_path)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 1679, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas\_libs\parsers.pyx", line 557, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
